### ISSUE TITLE
Migrate existing post-content from WordPress

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digital.gov-resources#17]
The goal is to see what items we need to change in the posts

**Comment by jeremyzilar** [comment]
WP Image format that needs to be filtered for. There are **838** of these
```
<div id="attachment_146612" style="width: 260px" class="wp-caption alignright">
  <img class="size-full wp-image-146612 " src="https://s3.amazonaws.com/sitesusa/wp-content/uploads/sites/212/2011/11/250-x-167-Stuart-Barr_Fighting-Topis_Nov17th2008_Creative-Commons-BY-NC-SA-2.jpg" alt="A photo from flickr of two Topis (antelopes) fighting, head-butting each other" width="250" height="167" />
  
  <p class="wp-caption-text">
    Stuart Barr, Fighting Topis, Creative Commons BY-NC-SA 2.0
  </p>
</div>
```
Possibly transformed to the picture-key format:
```
{% picture [preset] path/to/img.jpg [source_key: path/to/alt/img.jpg] [attribute="value"] %}
```

**Comment by jeremyzilar** [comment]
There are **458** of these images linking to themselves as well...

```
[<img class="alignright wp-image-100002 size-medium" src="https://s3.amazonaws.com/sitesusa/wp-content/uploads/sites/212/2013/12/GSA-New-Media-250x157.jpg" alt="Image of IPad." width="250" height="157" />](https://s3.amazonaws.com/sitesusa/wp-content/uploads/sites/212/2013/12/GSA-New-Media.jpg)
```

**Comment by jeremyzilar** [comment]
Current Bulk import branch here: https://github.com/GSA/digital.gov/tree/bulk-import-posts

**Comment by jeremyzilar** [comment]
@thisisdano Is this what we want for images?
```
{% picture [preset] http://localhost/wp/wp-content/uploads/2017/05/cat-mica.jpg [source_key: http://localhost/wp/wp-content/uploads/2017/05/cat-mica.jpg] [attribute="caption text"] %}
```
The paths for the images will be at the AWS CDN but for the formatting of the liquid tag, can this be something to aim for in the next test?

**Comment by thisisdano** [comment]
@jz I'm going to keep a list of migration issues here.

- Compile time is much slower post migration, I wonder why? (actually, maybe this is just on first compile, otherwise comparable...)
- Tags should (when possible) match the slugs in data/tag.yml (all these outputs can be controlled on the back end, this is just for getting the right urls)
  - [ ] replace ampersands with `and`
  - [ ] replace `U.S.` with `US`
- Categories should (when possible) match the slugs in data/categories.yml
  - [ ] replace ampersands with `and` (we can control whether ampersands appear on the back end)
- New embed/image shortcodes
  - [ ] images
  - [ ] YouTube
  - [ ] Twitter
  - [ ] Instagram

**Comment by aalikaram** [comment]
🛑DEPRECATED🛑 - Repo no longer being maintained #17
